version: '3.7'

services:
  prices-api:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./
      dockerfile: docker/price.api.dockerfile
    image: "hmq.price.api:${IMAGE_TAG:-compose}"
    environment:
      - "ENVIRONMENT=${ENVIRONMENT:-compose}"
      - "LOG_LEVEL=${LOG_LEVEL:-INFO}"
      - "CONFIG_PATH=${CONFIG_PATH:-/etc/hmq/compose.price-api.yaml}"
      - "LISTEN=${LISTEN:-}"
      - "PORT=${PORT:-8080}"
      - "OPENAPI_PATH=${OPENAPI_PATH:-/usr/local/share/prices.openapi.yaml}"
      - "GOOGLE_APPLICATION_CREDENTIALS=/secret/gcloud.json"
      - "DATASTORE_PROJECT_ID=${DATASTORE_PROJECT_ID:-}"
      - "DATASTORE_PRICE_ASSETS_KIND=${DATASTORE_PRICE_ASSETS_KIND:-}"
      - "PERMANENT_TOKEN=${PERMANENT_TOKEN:-}"
      - "BASE_URL=${BASE_URL:-}"
    ports:
      - "${PUBLIC_PORT:-8080}:${PORT:-8080}"
    networks:
      app:
        ipv4_address: ${NETWORK_PREFIX:-173.200.201}.10
        aliases:
          - price-api.${APP_NAME:-app}.compose
    volumes:
      - ./.local/secret:/secret
      - ./etc:/etc/hmq

networks:
  app:
    ipam:
      config:
        - subnet: "${NETWORK_PREFIX:-173.200.202}.0/24"
