assets:
  - btc
  - eth
  - usd
  - eur
  - rub
  - bnb
  - cny
  - jpy
currencies:
  btc: btc
  eth: eth
  usd: usd
  eur: eur
  rub: rub
  bnb: bnb
  cny: cny
  jpy: jpy
  tzs: usd
  ugx: usd
  frw: usd
  krw: usd
