assets:
  - btc
  - eth
  - bnb
  - usd
  - eur
  - rub
  - cny
  - jpy
currencies:
  btc: btc
  eth: eth
  bnb: bnb
  usd: usd
  eur: eur
  rub: rub
  cny: cny
  jpy: jpy
  tzs: usd
  ugx: usd
  rwf: usd
  krw: usd
providers:
  - name: PancakeSwap Savy
    every: 5m
    pancakeswap:
      symbols:
        - wbgl
        - busd
      asset_mapper: usd
  - name: CoinGecko Stables
    every: 5m
    coingecko:
      currencies:
        - btc
        - eth
        - usd
        - eur
        - rub
        - bnb
        - cny
        - jpy
      symbols:
        - eth
        - hmq
        - btc
        - usdt
        - usdc
  - name: Coingecko Others
    every: 5m
    coingecko:
      currencies:
        - btc
        - eth
        - usd
        - eur
        - rub
        - bnb
        - cny
        - jpy
      symbols:
        - zcn
        - zrx
        - 1inch
        - aave
        - aeth
        - aioz
        - akita
        - albt
        - amp
        - ampl
        - matter
        - apy
        - ant
        - armor
        - arnxm
        - atri
        - audio
        - rep
        - axs
        - axn
        - bal
        - band
        - bond
        - bart
        - base
        - bat
        - bel
        - bepro
        - bbtc
        - bird
        - blank
        - bfc
        - bondly
        - bbr
        - bmi
        - bins
        - adx
        - card
        - cell
        - cel
        - chads
        - chain
        - cgg
        - link
        - comp
        - cvp
        - conv
        - coti
        - cws
        - cc10
        - xcur
        - crv
        - core
        - cfi
        - dai
        - dec
        - dyp
        - dpi
        - dgvc
        - dego
        - delta
        - dev
        - dextf
        - dext
        - buidl
        - df
        - dia
        - dhc
        - dmg
        - elon
        - doki
        - ddim
        - sale
        - enj
        - eth2x-fli
        - push
        - emax
        - dip
        - ern
        - lend
        - id
        - xed
        - exnt
        - fei
        - frm
        - fxf
        - fcl
        - frax
        - fsw
        - fun
        - fx
        - fyz
        - dao
        - gth
        - mana
        - gysr
        - giv
        - gno
        - govi
        - glq
        - gro
        - farm
        - bnb
        - hegic
        - hez
        - hex
        - hoge
        - hot
        - cream
        - rlc
        - inj
        - jup
        - k21
        - keep
        - kp3r
        - kine
        - kex
        - kishu
        - pnk
        - knc
        - kyl
        - ltx
        - lpool
        - lead
        - leash
        - lgo
        - lgcy
        - lrc
        - lto
        - lst
        - lyxe
        - lusd
        - maha
        - mkr
        - om
        - mask
        - matic
        - mcb
        - meme
        - mta
        - mvi
        - mtlx
        - minds
        - mir
        - mod
        - mph
        - mco2
        - coin
        - nexo
        - noia
        - nfy
        - nu
        - ocean
        - omg
        - room
        - orai
        - oxt
        - ogn
        - trac
        - orn
        - ovr
        - paid
        - prq
        - paxg
        - epan
        - perp
        - pickle
        - plr
        - mark
        - pnt
        - pkf
        - polk
        - pols
        - pmon
        - pool
        - poolz
        - ptf
        - pbtc
        - mint
        - npxs
        - pundix
        - qnt
        - qrx
        - rai
        - rly
        - ramp
        - rari
        - razor
        - rio
        - rfox
        - reef
        - renbtc
        - ren
        - req
        - rsr
        - revv
        - rfuel
        - xrt
        - rpl
        - root
        - rbc
        - sfi
        - shib
        - si
        - skl
        - skey
        - smartcredit
        - slp
        - xor
        - srk
        - spi
        - stbz
        - susd
        - dsla
        - stmx
        - strong
        - super
        - surf
        - sushi
        - swfl
        - sxp
        - sync
        - snx
        - tad
        - tbtc
        - 10set
        - tbc
        - tvk
        - dyt
        - grt
        - ring
        - sand
        - get
        - rune
        - lon
        - tkn
        - bid
        - torn
        - tower
        - tribe
        - tusd
        - tru
        - swap
        - uma
        - umb
        - ersdl
        - ubt
        - uncx
        - layer
        - umx
        - unn
        - socks
        - unistake
        - duck
        - trade
        - uni
        - zcx
        - uft
        - marsh
        - vra
        - vsp
        - vidya
        - visr
        - waxe
        - weth
        - whale
        - wise
        - woo
        - world
        - wanatha
        - wbtc
        - luna
        - xcad
        - stake
        - xfi
        - xio
        - xtk
        - yfi
        - yf-dai
        - yld
        - yop
        - zefu
  - name: FIAT
    every: 10m
    geocurrency:
      api_key: "|GETGEO_API_KEY"
      symbols:
        - usd
        - eur
        - rub
        - cny
        - jpy
        - tzs
        - ugx
        - krw
        - rwf
      currencies:
        USD: usd
        EUR: eur
        RUB: rub
        CNY: cny
        JPY: jpy
        TZS: tzs
        UGX: ugx
        KRW: krw
        RWF: rwf
consumers:
  - name: Datastore PriceStorage
    google_datastore:
      project_id: humaniq-168420
      price_assets_kind: production_price_assets
  - name: BSC PriceOracle
    tokens:
      - symbol: wbgl
        currency: usd
      - symbol: busd
        currency: usd
    price_oracle:
      network_key: BSC
      contract_address_hex: 0x5641d752955C089Df17D04A3ac1EFD5Ba590fB7b
      client_private_key: "|BSC_ORACLE_PRIVATE_KEY"
thresholds:
  default:
    percent_threshold: 1
    time_threshold: 1h
  custom:
    - symbol: wbgl
      percent_threshold: 5
    - symbol: busd
      percent_threshold: 0.25
asset_files:
  coingecko:
    - /etc/hmq/assets/coingecko.assets.yaml
  eth:
    - /etc/hmq/assets/network.bsc.assets.yaml
