openapi: 3.0.3
info:
  title: 'Human-OID cache API'
  version: '1.0.0'
  description: 'HumanOID API for caching signup-bot data/keys'
servers:
  - url: 'http://104.155.77.190/api/v1'
    description: 'development/testing environment'
components:
  schemas:
    APIError:
      type: object
      properties:
        status:
          type: string
        payload:
          type: any
    PriceRecord:
      type: object
      properties:
        source:
          type: string
          description: the source of the price data
        symbol:
          type: string
          description: Token key representation
        currency:
          type: string
          description: currency representation
        price:
          type: number
        previousPrice:
          type: number
        timeStamp:
          type: string
paths:
  /price/{symbol}:
    get:
      tags:
        - prices
      parameters:
        - name: symbol
          in: path
          required: true
        - name: currency
          in: query
          required: false
          default: 'ETH'
      responses:
        200:
          description: price value for symbol given
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceRecord'
        400:
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        404:
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        500:
          description: internal error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/APIError'
  /prices:
    get:
      tags:
        - prices
      parameters:
        - name: payload
          in: body
          required: false
          description: list of symbols needed
          schema:
            type: array
            items:
              type: string
      responses:
        200:
          description: price values for symbol given
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PriceRecord'
        400:
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        404:
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        500:
          description: internal error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/APIError'
