assets:
  - btc
  - eth
  - usd
  - eur
  - rub
  - bnb
  - cny
  - jpy
currencies:
  btc: btc
  eth: eth
  usd: usd
  eur: eur
  rub: rub
  bnb: bnb
  cny: cny
  jpy: jpy
  tzs: usd
  ugx: usd
  frw: usd
  krw: usd
providers:
  - name: coingecko-eth-hmq
    type: coingecko
    symbols:
      ethereum: eth
      humaniq: hmq
      bitcoin: btc
    currencies:
      btc: btc
      eth: eth
      usd: usd
      eur: eur
      rub: rub
      bnb: bnb
      cny: cny
      jpy: jpy
  - name: coingecko
    type: coingecko
    symbols:
      0chain: zcn
      0x-wormhole: zrx
      1inch-wormhole: 1inch
      aave-wormhole: aave
      aetherius: aeth
      aioz-network: aioz
      akita-inu: akita
      allianceblock: albt
      amp-wormhole: amp
      ampleforth-wormhole: ampl
      antimatter: matter
      apy-finance: apy
      aragon: ant
      armor: armor
      armor-nxm: arnxm
      atari: atri
      audius-wormhole: audio
      augur: rep
      axie-infinity: axs
      axion: axn
      balancer: bal
      band-protocol: band
      barnbridge: bond
      bartertrade: bart
      base-protocol: base
      basic-attention-token-wormhole: bat
      belrium: bel
      bepro-network: bepro
      binance-wrapped-btc: bbtc
      birdy-finance: bird
      blank: blank
      bologna-fc-fan-token: bfc
      bondly: bondly
      boolberry: bbr
      bridge-mutual: bmi
      bsocial: bins
      cardanomics: adx
      cardstack: card
      cellframe: cell
      celsius-wormhole: cel
      chads-vc: chads
      chain-games: chain
      chain-guardians: cgg
      chainlink-wormhole: link
      compound-wormhole: comp
      concentrated-voting-power: cvp
      convergence: conv
      coti: coti
      crowns: cws
      cryptocurrency-top-10-tokens-index: cc10
      curate: xcur
      curve-dao-token-wormhole: crv
      cvault-finance: core
      cyberfi: cfi
      dai-wormhole: dai
      decentr: dec
      defi-yield-protocol: dyp
      defipulse-index: dpi
      degenvc: dgvc
      dego-finance: dego
      delta-financial: delta
      dev-protocol: dev
      dextf: dextf
      dextools: dext
      dfohub: buidl
      dforce-token: df
      dia-data: dia
      diamond-hands-token: dhc
      dmm-governance: dmg
      dogelon-mars-wormhole: elon
      doki-doki-finance: doki
      duckdaodime: ddim
      dxsale-network: sale
      enjin-wormhole: enj
      eth-2x-flexible-leverage-index: eth2x-fli
      ethereum-push-notification-service: push
      ethereummax: emax
      etherisc: dip
      ethernity-chain: ern
      ethlend: lend
      everid: id
      exeedme: xed
      exnetwork-token: exnt
      fei-usd: fei
      ferrum-network: frm
      finxflo: fxf
      fractal: fcl
      frax-wormhole: frax
      fsw-token: fsw
      funfair: fun
      fx-coin: fx
      fyooz: fyz
      gamedao: dao
      gather: gth
      genesis-mana: mana
      geyser: gysr
      givly-coin: giv
      gnosis: gno
      govi: govi
      graphlinq-protocol: glq
      growth-defi: gro
      harvest-finance: farm
      heco-peg-bnb: bnb
      hegic: hegic
      hermez-network-token: hez
      hex: hex
      hoge-finance: hoge
      hydro-protocol: hot
      icecream-finance: cream
      iexec-rlc: rlc
      injective-protocol: inj
      jupiter: jup
      k21: k21
      keep-network-wormhole: keep
      keep3rv1-wormhole: kp3r
      kine-protocol: kine
      kira-network: kex
      kishu-inu: kishu
      kleros: pnk
      kyber-network-crystal: knc
      kylin-network: kyl
      lattice-token: ltx
      launchpool: lpool
      lead-token: lead
      leash: leash
      legolas-exchange: lgo
      lgcy-network: lgcy
      loopringcoin-v2-wormhole: lrc
      lto-network: lto
      luckyseventoken: lst
      lukso-token: lyxe
      lusd: lusd
      mahadao: maha
      maker: mkr
      mantra-dao: om
      mask-vault-nftx: mask
      matic-network: matic
      mcdex: mcb
      memeverse: meme
      metaaxis: mta
      metaverse-index: mvi
      mettalex: mtlx
      minds: minds
      mirror-protocol: mir
      modefi: mod
      morpher: mph
      moss-carbon-credit: mco2
      mushroom-coin: coin
      nexo: nexo
      noia-network: noia
      non-fungible-yearn: nfy
      nucypher: nu
      ocean-protocol: ocean
      omisego: omg
      option-room: room
      oraichain-token: orai
      orchid-protocol: oxt
      origin-protocol: ogn
      origintrail: trac
      orion-protocol: orn
      ovr: ovr
      paid-network: paid
      parsiq: prq
      paxos-gold-wormhole: paxg
      paypolitan-token: epan
      perpetual-wormhole: perp
      pickle-finance: pickle
      pillar: plr
      plato-farm: mark
      pnetwork: pnt
      polkafoundry: pkf
      polkamarkets: polk
      polkastarter: pols
      polychain-monsters: pmon
      pool-token: pool
      poolz-finance: poolz
      powertrade-fuel: ptf
      ptokens-btc: pbtc
      public-mint: mint
      pundi-x: npxs
      pundi-x-2: pundix
      quant-network: qnt
      quiverx: qrx
      rai-token: rai
      rally-2: rly
      ramp: ramp
      rari-token: rari
      razor-network: razor
      realio-network: rio
      redfox-labs-2: rfox
      reef-finance: reef
      renbtc: renbtc
      republic-protocol: ren
      request-network: req
      reserve-rights-wormhole: rsr
      revv: revv
      rio-defi: rfuel
      robonomics-network: xrt
      rocket-pool-wormhole: rpl
      rootkit: root
      ruby-currency: rbc
      saffron-finance: sfi
      shiba-inu-wormhole: shib
      siren: si
      skale: skl
      skey-network: skey
      smartcredit-token: smartcredit
      smooth-love-potion-wormhole: slp
      sora: xor
      sparkpoint: srk
      spartan-index: spi
      stabilize: stbz
      stabilize-usd: susd
      stacktical: dsla
      storm: stmx
      strong: strong
      superfarm: super
      surf-finance: surf
      sushi-wormhole: sushi
      swapfolio: swfl
      swipe-wormhole: sxp
      sync-network: sync
      synthetix-network-token-wormhole: snx
      tadpole-token: tad
      tbtc: tbtc
      tenset: 10set
      terablock: tbc
      terra-virtua-kolect: tvk
      tether-avalanche-bridged-usdt-e: usdt
      the-dynasty: dyt
      the-graph-wormhole: grt
      the-one-ring: ring
      the-sandbox-wormhole: sand
      themis: get
      thorchain-erc20: rune
      tokenlon: lon
      tokonft: tkn
      topbidder: bid
      tornado-cash: torn
      tower: tower
      tribe-wormhole: tribe
      true-usd: tusd
      truefi: tru
      trustswap: swap
      uma: uma
      umbrella-network: umb
      unfederalreserve: ersdl
      unibright: ubt
      unicrypt-2: uncx
      unilayer: layer
      unimex-network: umx
      union-protocol-governance-token: unn
      unisocks: socks
      unistake: unistake
      unit-protocol-duck: duck
      unitrade: trade
      universe-token: uni
      unizen: zcx
      unlend-finance: uft
      unmarshal: marsh
      usd-coin-avalanche-bridged-usdc-e: usdc
      verasity: vra
      vesper-finance: vsp
      vidya: vidya
      visor: visr
      waxe: waxe
      weth: weth
      white-whale: whale
      wise-token11: wise
      woo-network: woo
      world-token: world
      wrapped-anatha: wanatha
      wrapped-btc-wormhole: wbtc
      wrapped-terra: luna
      xcad-network: xcad
      xdai-stake: stake
      xfinance: xfi
      xio: xio
      xtoken: xtk
      yearn-finance-wormhole: yfi
      yfdai-finance: yf-dai
      yield-app: yld
      yield-optimization-platform: yop
      zenfuse: zefu
      zoints: zee
    currencies:
      btc: btc
      eth: eth
      usd: usd
      eur: eur
      rub: rub
      bnb: bnb
      cny: cny
      jpy: jpy
  - name: geocurrency
    type: geocurrency
    symbols:
      TZS: tzs
      UGX: ugx
      FRW: frw
      KRW: krw
    currencies:
      usd: usd
      eur: eur
diffs:
  usdc: 100
  usdt: 100
  1inch: 100
  adx: 100
  arnxm: 100
  audio: 100
  bbr: 100
  bbtc: 1000
  bins: 100
  btc: 100
  cc10: 100
  chads: 100
  coin: 100
  core: 100
  dao: 100
  delta: 1000
  dextf: 1000
  dgvc: 100
  dhc: 100
  dyt: 1000
  elon: 100
  exnt: 100
  fei: 100
  fun: 1000
  giv: 100
  gno: 1000
  gysr: 1000
  krw: 1000
  lend: 1000
  lgo: 100
  lst: 100
  mta: 1000
  nfy: 1000
  npxs: 1000
  ovr: 1000
  pbtc: 1000
  pool: 1000
  qrx: 100
  rai: 100
  rari: 100
  renbtc: 1000
  rfuel: 1000
  ring: 100
  root: 100
  rsr: 100
  smartcredit: 1000
  socks: 1000
  stbz: 1000
  susd: 100
  sync: 1000
  tad: 100
  tkn: 1000
  tusd: 1000
  tzs: 1000
  ugx: 1000
  visr: 1000
  wbtc: 100
  weth: 1000
  whale: 100
  xfi: 100
  xtk: 1000
  zee: 100
force_update_seconds:
  usdc: 14400
  usdt: 14400
  1inch: 14400
  adx: 14400
  arnxm: 14400
  audio: 14400
  bbr: 14400
  bbtc: 14400
  bins: 14400
  btc: 14400
  cc10: 14400
  chads: 14400
  coin: 14400
  core: 14400
  dao: 14400
  delta: 14400
  dextf: 14400
  dgvc: 14400
  dhc: 14400
  dyt: 14400
  elon: 14400
  exnt: 14400
  fei: 14400
  fun: 14400
  giv: 14400
  gno: 14400
  gysr: 14400
  krw: 14400
  lend: 14400
  lgo: 14400
  lst: 14400
  mta: 14400
  nfy: 14400
  npxs: 14400
  ovr: 14400
  pbtc: 14400
  pool: 14400
  qrx: 14400
  rai: 14400
  rari: 14400
  renbtc: 14400
  rfuel: 14400
  ring: 14400
  root: 14400
  rsr: 14400
  smartcredit: 14400
  socks: 14400
  stbz: 14400
  susd: 14400
  sync: 14400
  tad: 14400
  tkn: 14400
  tusd: 14400
  tzs: 14400
  ugx: 14400
  visr: 14400
  wbtc: 14400
  weth: 14400
  whale: 14400
  xfi: 14400
  xtk: 14400
  zee: 14400
